### ISSUE TITLE
[Bug]: Header Two from Patterns tab is injecting the script!

### ISSUE THREAD

**Issue by ale-for-friend** [thewebforge/structeezy-docs#10]
### Contact Details

forchettina@gmail.com

### What happened?

A bug happened! I'm trying to follow the tut on youtube, and when I got into the step specified into the object it came out this all the script text, not the visual objects!

### Version

1.1.0

### Version

1.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hello @ale-for-friend ,
If you see the code, you Bricks settings are probabl no set to allow code execution in the editor.
Can you please make sure it COde execution is activated in Bricks -> Settings -> Builder Access -> Code Execution.
Thanks!

**Comment by cbontems** [comment]
No news. Please reopen if necessary.
