### ISSUE TITLE
[Idea]: Make the OxyProps Lite promotion optional

### ISSUE THREAD

**Issue by jrmyfranck** [thewebforge/structeezy-docs#11]
### Contact Details

jrmyfranck@gmail.com

### What would this feature do?

Currently, Structeezy creates an **`Install Plugins`** entry under **Plugins** in the admin menu, the content of which is a recommandation to install OxyProps Lite.
![Screenshot 2023-11-28 à 13 46 21](https://github.com/thewebforge/structeezy-docs/assets/25497483/56dea910-ef08-4b87-8a7c-ae3e32a1035f)

While it certainly makes sense from a business perspective and could be of value to users unfamiliar with it, I believe in some cases it doesn't make much sense:

- If a CSS framework is already detected by Structeezy (be that ACSS, Core or OxyProps), it wouldn’t really make sense to install another one.
- Or simply if the user isn’t keen on using this specific framework. 

Currently, I’m using a third-party plugin (ASE) to hide the menu entry, but I’d like a native option to hide this extra menu item I didn’t ask and have no use for.

Thanks for your consideration, @cbontems 

### What would be this feature settings?

I suppose it could be a simple checkbox, or alternatively the entire suggestion to install OxyProps Lite could be moved to the bottom of Structeezy’s **Settings** page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hi,
This is planned for a next update.

**Comment by cbontems** [comment]
Fixed in v1.2
