### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 2urn** [thewebforge/structeezy-docs#3]
### Contact Details

info@2urn.com

### What happened?

A bug happened! I am unable to see the Structeezy Admin pages on Chrome or Firefox. I disabled all other plugins to no avail.  I declined the Oxyprops lite install.

Pluigns:

Advanced Themer for Bricks (1.2.3) | by Maxime Beguin
BricksExtras (1.3.3) | by BricksExtras
Core Framework (1.1.0) | by Core Framework
HappyFiles Pro (1.8.2) | by Codeer
Meta Box (5.7.4) | by MetaBox.io
Meta Box AIO (1.21.4) | by MetaBox.io
Structeezy (0.4.0) | by Cédric Bontems - The Web Forge
Temporary Login Without Password (1.8.2) | by StoreApps

### Version

0.40

### Version

1.8.5

### What browsers are you seeing the problem on?

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hello @2urn ,
I am unable to reproduce with a similar plugins stack except for BricksExtra and Temporary Login Without Password.
Can you please give me access to an environment where this happens ?
Thanks for your help.
