### ISSUE TITLE
I cannot activate Structeezy on an Instawp site[Bug]: 

### ISSUE THREAD

**Issue by Sinovya** [thewebforge/structeezy-docs#8]
### Contact Details

dgebert@306digital.com

### What happened?

I am unable to activate the plugin on an InstWP site. I receive a "Sorry you are not allowed to access this page" message.

### Version

1.1.0

### Version

1.9.3

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hello @Sinovya,
I just checked and I have no problems activating your license on my test sites, so maybe there is something with instaWP.
Can you give me acces to your site so I can check ?

**Comment by cbontems** [comment]
Closing the issue. Please reopen a new one if needed.
