### ISSUE TITLE
[Bug]: CSS DEFAULT (Into: Preferences / css frameworks) injecting status

### ISSUE THREAD

**Issue by ale-for-friend** [thewebforge/structeezy-docs#9]
### Contact Details

forchettina@gmail.com

### What happened?

A bug happened! When I get into the CSS FRAMEWORK tab (Preferences) the Css Defaults were empty. I tried to switch between "None" and OxyProps" but nothing changed. So I click back to general and than on Css Framework again... and than all fields are populated with the correct data! I tried to switch again between the two option that I got, and nothing changes...it changes only if you always get back to general, or another tab and than back to CSS Framework. ;)

### Version

1.1.0

### Version

1.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Thanks @ale-for-friend,
This is a component rendering bug in the app. The settings are OK but not visible. By switching tab, you force rendering and they are visible. I need to fix it.
Thanks for reporting.

**Comment by cbontems** [comment]
Fixed in v1.5
